In [1]:
import numpy as np
import geopandas as gpd
import pandas as pd
import requests
from zipfile import ZipFile
from io import BytesIO
from pathlib import Path
import shutil

In [2]:
list(range(14))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

In [3]:
np.arange(0, 15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
df = pd.read_csv(
        "https://doi.glamos.ch/data/glacier_list/glacier_list.csv",
        skiprows=9,
        parse_dates=True,
        names=[
            "name",
            "id",
            "coordx",
            "coordy",
            "area",
            "survey_year",
            "length_change_data_available",
            "mass_balance_data_available",
            "volume_change_data_available",
        ],
    )

In [17]:
df.loc[121]

name                            Silvrettagletscher
id                                         A10g-05
coordx                                     2801722
coordy                                     1192164
area                                         2.665
survey_year                                 2014.0
length_change_data_available                     1
mass_balance_data_available                      1
volume_change_data_available                     1
Name: 121, dtype: object

In [6]:
df = df[df['mass_balance_data_available'] == 1][['id', 'coordx', 'coordy']]

In [18]:
mb = pd.read_csv(
        "https://doi.glamos.ch/data/massbalance/massbalance_fixdate.csv",
        skiprows=9,
        parse_dates=True,
        usecols=list(range(8)),
        names=[
            "name",
            "id",
            "observation_start",
            "observation_end_winter",
            "observation_end",
            "mass_balance_winter",
            "mass_balance_summer",
            "mass_balance_annual",
        ],
    )

In [19]:
mb

,name,id,observation_start,observation_end_winter,observation_end,mass_balance_winter,mass_balance_summer,mass_balance_annual
0,Silvrettagletscher,A10g-05,1914-10-01,1915-04-30,1915-09-30,1503,-1918,-415
1,Silvrettagletscher,A10g-05,1915-10-01,1916-04-30,1916-09-30,1415,-1034,381
2,Silvrettagletscher,A10g-05,1916-10-01,1917-04-30,1917-09-30,1872,-1900,-28
3,Silvrettagletscher,A10g-05,1917-10-01,1918-04-30,1918-09-30,1075,-1489,-414
4,Silvrettagletscher,A10g-05,1918-10-01,1919-04-30,1919-09-30,1862,-840,1022
...,...,...,...,...,...,...,...,...
1234,Vadret dal Corvatsch,E23-18,2020-10-01,2021-04-30,2021-09-30,922,-1804,-882
1235,Vadret dal Corvatsch,E23-18,2021-10-01,2022-04-30,2022-09-30,461,-4078,-3617
1236,Vadret dal Corvatsch,E23-18,2022-10-01,2023-04-30,2023-09-30,483,-2077,-1594
1237,Vadret dal Corvatsch,E23-18,2023-10-01,2024-04-30,2024-09-30,1433,-1919,-486
1238,Vadret dal Corvatsch,E23-18,2024-10-01,2025-04-30,2025-09-30,772,-2073,-1301

In [20]:
df = pd.merge(mb, df, on="id")[[
        "id",
        "observation_start",
        "observation_end_winter",
        "observation_end",
        "mass_balance_winter",
        "mass_balance_summer",
        "mass_balance_annual",
        "coordx",
        "coordy",
    ]]
df

,id,observation_start,observation_end_winter,observation_end,mass_balance_winter,mass_balance_summer,mass_balance_annual,coordx,coordy
0,A10g-05,1914-10-01,1915-04-30,1915-09-30,1503,-1918,-415,2801722,1192164
1,A10g-05,1915-10-01,1916-04-30,1916-09-30,1415,-1034,381,2801722,1192164
2,A10g-05,1916-10-01,1917-04-30,1917-09-30,1872,-1900,-28,2801722,1192164
3,A10g-05,1917-10-01,1918-04-30,1918-09-30,1075,-1489,-414,2801722,1192164
4,A10g-05,1918-10-01,1919-04-30,1919-09-30,1862,-840,1022,2801722,1192164
...,...,...,...,...,...,...,...,...,...
1234,E23-18,2020-10-01,2021-04-30,2021-09-30,922,-1804,-882,2783300,1143402
1235,E23-18,2021-10-01,2022-04-30,2022-09-30,461,-4078,-3617,2783300,1143402
1236,E23-18,2022-10-01,2023-04-30,2023-09-30,483,-2077,-1594,2783300,1143402
1237,E23-18,2023-10-01,2024-04-30,2024-09-30,1433,-1919,-486,2783300,1143402
1238,E23-18,2024-10-01,2025-04-30,2025-09-30,772,-2073,-1301,2783300,1143402

In [21]:
dir = Path('../data/tmp/glacier_inventory/')
shutil.rmtree(dir, ignore_errors=True)
dir.mkdir(parents=True)

r = requests.get("https://doi.glamos.ch/data/inventory/inventory_sgi2010_r2010.zip", stream=True)
with ZipFile(BytesIO(r.content)) as fd:
    fd.extractall(dir)

In [22]:
deb = gpd.read_file(dir / 'SGI_2016_debriscover.shp')
deb[deb['sgi-id'] == 'B55-19'].plot()

DataSourceError: ../data/tmp/glacier_inventory/SGI_2016_debriscover.shp: No such file or directory

In [23]:
center = gpd.read_file(dir / 'SGI_2016_centerlines.shp')
center[center['sgi-id'] == 'B55-19'].plot()

DataSourceError: ../data/tmp/glacier_inventory/SGI_2016_centerlines.shp: No such file or directory

In [24]:
gl = gpd.read_file(dir / 'SGI_2016_glaciers.shp')
gl

DataSourceError: ../data/tmp/glacier_inventory/SGI_2016_glaciers.shp: No such file or directory

In [25]:
gl[gl['sgi-id'] == 'E22-16']

NameError: name 'gl' is not defined

In [ ]:
ice = gpd.read_file(dir / 'SGI_2016_icedivides.shp')
ice

In [ ]:
ice[ice['sgi-id_a'] == 'B55-19'].plot()

In [ ]:
deb[['sgi-id', 'geometry']]

In [ ]:
gl[['sgi-id', 'geometry']].to_parquet('../data/glacier_geometry_2013-2018.parquet')

In [ ]:
deb[['sgi-id', 'geometry']].to_parquet('../data/debris_geometry_2011-2017.parquet')

In [ ]:
deb

In [ ]:
deb.describe()

In [ ]:
gl = gpd.read_file(dir / 'SGI_2010.shp')

In [ ]:
gl

In [ ]:
gl[gl.SGI == 'B51-41']